---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: Adicione e remova as credenciais do provedor de nuvem da sua conta a qualquer momento. O Astra usa essas credenciais para provisionar recursos em seu nome. 
---
= Adicione e remova credenciais
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Adicione e remova credenciais de fornecedores de nuvem privada locais, como o ONTAP S3, clusters do Kubernetes gerenciados com o OpenShift ou clusters do Kubernetes não gerenciados da sua conta a qualquer momento. O Astra Control Center usa essas credenciais para descobrir clusters de Kubernetes e as aplicações nos clusters e para provisionar recursos em seu nome.

Observe que todos os usuários do Astra Control Center compartilham os mesmos conjuntos de credenciais.



== Adicionar credenciais

Você pode adicionar credenciais ao Astra Control Center ao gerenciar clusters. Para adicionar credenciais adicionando um novo cluster, link:../get-started/add-cluster.html["Adicionar um cluster do Kubernetes"]consulte .


NOTE: Se você criar seu próprio arquivo kubeconfig, você deve definir apenas um elemento de contexto * nele.  https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Documentação do Kubernetes"^]Consulte para obter informações sobre a criação de arquivos kubeconfig.



== Remover credenciais

Remova as credenciais de uma conta a qualquer momento. Você só deve remover credenciais após link:unmanage.html["desgerenciar todos os clusters associados"]o .


NOTE: O primeiro conjunto de credenciais que você adiciona ao Astra Control Center está sempre em uso porque o Astra Control Center usa as credenciais para se autenticar no bucket do backup. É melhor não remover essas credenciais.

.Passos
. Selecione *conta*.
. Selecione a guia *Credentials*.
. Selecione o menu Opções na coluna *Estado* para as credenciais que você deseja remover.
. Selecione *Remover*.
. Digite a palavra "remove" para confirmar a exclusão e selecione *Yes, Remove Credential*.


.Resultado
O Astra Control Center remove as credenciais da conta.
