---
sidebar: sidebar 
permalink: use/unmanage.html 
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster, kubernetes, astra, astra control 
summary: Remova do Astra Control todas as aplicações ou computação que você não deseja mais gerenciar. 
---
= Desgerenciar aplicativos e clusters
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Remova todas as aplicações ou clusters que você não deseja mais gerenciar do Astra Control Center.



== Desgerenciar um aplicativo

Pare de gerenciar aplicações que não deseja mais fazer backup, snapshot ou clonar a partir do Astra Control Center.

Quando você desgerencia um aplicativo:

* Todos os backups e snapshots existentes serão excluídos.
* Aplicativos e dados permanecem disponíveis.


.Passos
. Na barra de navegação à esquerda, selecione *aplicações*.
. Selecione a aplicação.
. No menu Opções na coluna ações, selecione *Desgerenciar*.
. Reveja as informações.
. Digite "Unmanage" (Desgerenciar) para confirmar.
. Selecione *Sim, desgerenciar o aplicativo*.


.Resultado
O Astra Control Center deixa de gerenciar a aplicação.



== Desgerenciar um cluster

Pare de gerenciar o cluster que não deseja mais gerenciar a partir do Astra Control Center.


NOTE: Antes de desgerenciar o cluster, você deve desgerenciar os aplicativos associados ao cluster.

Quando você desgerencia um cluster:

* Essa ação impede que o cluster seja gerenciado pelo Astra Control Center. Ele não faz alterações na configuração do cluster e não exclui o cluster.
* O Astra Control Provisioner ou o Astra Trident não serão desinstalados do cluster. https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["Saiba como desinstalar o Astra Trident"^].


.Passos
. Na barra de navegação à esquerda, selecione *clusters*.
. Marque a caixa de seleção do cluster que você não deseja mais gerenciar.
. No menu Opções na coluna *ações*, selecione *Desgerenciar*.
. Confirme se deseja desgerenciar o cluster e selecione *Sim, desgerenciar o cluster*.


.Resultado
O status do cluster muda para *Remover*. Depois disso, o cluster será removido da página *clusters* e não será mais gerenciado pelo Astra Control Center.


IMPORTANT: O desgerenciamento do cluster remove todos os recursos que foram instalados para o envio de dados de telemetria.
